### ISSUE TITLE
Polish 

### ISSUE THREAD

**Issue by mosiojar** [ysnows/enconvo#1]
Hi,
Can you add Polish to the application?
Greetings
JM

**Comment by ysnows** [comment]
没问题，将在下个版本加入

**Comment by ysnows** [comment]
没问题，将在下个版本加入

@mosiojar

**Comment by ysnows** [comment]
No problem, it will be added in the next version.

@mosiojar

**Comment by mosiojar** [comment]
Super thanks 
JM

**Comment by ysnows** [comment]
@mosiojar added

**Comment by mosiojar** [comment]
Thank you, where can I make the Polish language available so that I can,
for example, do a translation?
[image: image.png]

wt., 5 gru 2023 o 03:34 ysnows ***@***.***> napisał(a):
