### ISSUE TITLE
LM studio 

### ISSUE THREAD

**Issue by mosiojar** [ysnows/enconvo#3]
I have a problem connecting to the local server with LM Sudio the following error appears: 

errorTypeError: Cannot read properties of undefined (reading 'message')

**Comment by ysnows** [comment]
Sorry for this error~ , a new version will be published today to resolve this issue



At 2023-12-28 17:16:35, "mosiojar" ***@***.***> wrote:

I have a problem connecting to the local server with LM Sudio the following error appears:

errorTypeError: Cannot read properties of undefined (reading 'message')

**Comment by ysnows** [comment]
Update to the newest version please ~
