### ISSUE TITLE
创建知识库的时候，报错

### ISSUE THREAD

**Issue by tobemaster56** [ysnows/enconvo#4]
使用该地址下载的 pdf 文件，创建知识库

https://assets.thebrain.com/documents/TheBrain14/TheBrain14-User-Guide-v01.pdf

结果：报错
<img width="625" alt="image" src="https://github.com/ysnows/enconvo/assets/8998761/2e67460b-d766-46a0-bbca-6934fd44d459">

预期：成功

**Comment by ysnows** [comment]
![image](https://github.com/ysnows/enconvo/assets/11255869/d04cb96e-d3eb-4d7d-8211-f685042c4602)

修复了，更新一下插件

**Comment by tobemaster56** [comment]
我点击了刷新，刷不出来，我看网页上，也有问题

![2024-04-30 17 36 14](https://github.com/ysnows/enconvo/assets/8998761/95339ae1-0885-4c54-b621-8a17a3674642)

**Comment by tobemaster56** [comment]
谢谢，已经好了
